package modelo;
// Generated 22-May-2017 20:03:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * AaClave generated by hbm2java
 */
public class AaClave  implements java.io.Serializable {


     private BigDecimal id;
     private AaUsuario aaUsuario;
     private String aplicacion;
     private String contrasena;
     private String descripcion;

    public AaClave() {
    }

    public AaClave(BigDecimal id, AaUsuario aaUsuario, String aplicacion, String contrasena, String descripcion) {
       this.id = id;
       this.aaUsuario = aaUsuario;
       this.aplicacion = aplicacion;
       this.contrasena = contrasena;
       this.descripcion = descripcion;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public AaUsuario getAaUsuario() {
        return this.aaUsuario;
    }
    
    public void setAaUsuario(AaUsuario aaUsuario) {
        this.aaUsuario = aaUsuario;
    }
    public String getAplicacion() {
        return this.aplicacion;
    }
    
    public void setAplicacion(String aplicacion) {
        this.aplicacion = aplicacion;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


