package modelo;
// Generated 22-May-2017 20:03:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AaUsuario generated by hbm2java
 */
public class AaUsuario  implements java.io.Serializable {


     private BigDecimal id;
     private String nombre;
     private String contrasena;
     private Set aaClaves = new HashSet(0);

    public AaUsuario() {
    }

	
    public AaUsuario(BigDecimal id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public AaUsuario(BigDecimal id, String nombre, String contrasena, Set aaClaves) {
       this.id = id;
       this.nombre = nombre;
       this.contrasena = contrasena;
       this.aaClaves = aaClaves;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set getAaClaves() {
        return this.aaClaves;
    }
    
    public void setAaClaves(Set aaClaves) {
        this.aaClaves = aaClaves;
    }




}


